/**
 * Service Worker Template.
 * Copy this to your public/sw.js file and customize as needed.
 *
 * @example
 * // In your public/sw.js file:
 * import { setupSWHandlers, createDefaultSyncHandler } from '@oxog/synckit/sw'
 *
 * // Define your executor function
 * async function executor(operations) {
 *   const results = []
 *   for (const operation of operations) {
 *     const response = await fetch('/api/sync', {
 *       method: 'POST',
 *       headers: { 'Content-Type': 'application/json' },
 *       body: JSON.stringify(operation),
 *     })
 *     results.push(await response.json())
 *   }
 *   return results
 * }
 *
 * // Set up handlers
 * setupSWHandlers({
 *   tagPrefix: 'my-app-sync',
 *   onSync: createDefaultSyncHandler(executor),
 *   enableLogging: true,
 * })
 */

/**
 * Example service worker template code.
 * This is a string that can be used to generate a service worker file.
 */
export const SERVICE_WORKER_TEMPLATE = `// SyncKit Service Worker
// Generated by @oxog/synckit

// Import SyncKit SW utilities
// Note: Adjust the import path based on your bundler
import { setupSWHandlers, createDefaultSyncHandler } from '@oxog/synckit/sw'

// Define your sync executor
// This function receives pending operations and should sync them to your backend
async function executor(operations) {
  const results = []

  for (const operation of operations) {
    try {
      // Example: Send to your API endpoint
      const response = await fetch('/api/sync', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(operation),
      })

      if (!response.ok) {
        throw new Error(\`HTTP error! status: \${response.status}\`)
      }

      const result = await response.json()
      results.push(result)
    } catch (error) {
      console.error('Sync operation failed:', error)
      throw error // Rethrow to trigger retry
    }
  }

  return results
}

// Set up service worker event handlers
setupSWHandlers({
  tagPrefix: 'synckit-sync',
  onSync: createDefaultSyncHandler(executor),
  enableLogging: process.env.NODE_ENV === 'development',
})

// Optional: Add custom message handlers
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'CUSTOM_ACTION') {
    // Handle custom actions
    console.log('Custom action received:', event.data)
  }
})

// Install event
self.addEventListener('install', (event) => {
  console.log('Service Worker installing...')
  // Force the waiting service worker to become the active service worker
  self.skipWaiting()
})

// Activate event
self.addEventListener('activate', (event) => {
  console.log('Service Worker activating...')
  // Claim clients immediately
  event.waitUntil(self.clients.claim())
})
`

/**
 * Generate a service worker file with custom configuration.
 */
export function generateServiceWorker(options: {
  /**
   * Tag prefix for sync events.
   * @default 'synckit-sync'
   */
  tagPrefix?: string

  /**
   * API endpoint for syncing operations.
   * @default '/api/sync'
   */
  apiEndpoint?: string

  /**
   * Enable logging in development.
   * @default true
   */
  enableLogging?: boolean

  /**
   * Additional custom code to inject.
   */
  customCode?: string
}): string {
  const {
    tagPrefix = 'synckit-sync',
    apiEndpoint = '/api/sync',
    enableLogging = true,
    customCode = '',
  } = options

  return `// SyncKit Service Worker
// Generated by @oxog/synckit

import { setupSWHandlers, createDefaultSyncHandler } from '@oxog/synckit/sw'

async function executor(operations) {
  const results = []

  for (const operation of operations) {
    try {
      const response = await fetch('${apiEndpoint}', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(operation),
      })

      if (!response.ok) {
        throw new Error(\`HTTP error! status: \${response.status}\`)
      }

      const result = await response.json()
      results.push(result)
    } catch (error) {
      console.error('Sync operation failed:', error)
      throw error
    }
  }

  return results
}

setupSWHandlers({
  tagPrefix: '${tagPrefix}',
  onSync: createDefaultSyncHandler(executor),
  enableLogging: ${enableLogging},
})

${customCode}

self.addEventListener('install', (event) => {
  console.log('Service Worker installing...')
  self.skipWaiting()
})

self.addEventListener('activate', (event) => {
  console.log('Service Worker activating...')
  event.waitUntil(self.clients.claim())
})
`
}
