/**
 * Generate a unique ID for operations.
 *
 * Format: {prefix}_{timestamp}_{random}
 * - Collision-resistant (timestamp + random)
 * - Sortable (timestamp-based)
 * - Human-readable with prefix
 *
 * @param prefix - Prefix for the ID (default: 'op')
 * @returns Unique ID string
 *
 * @example
 * ```ts
 * const id1 = generateId() // 'op_l8x9k2_a3b4c5d6'
 * const id2 = generateId('batch') // 'batch_l8x9k3_x7y8z9'
 * ```
 */
export function generateId(prefix: string = 'op'): string {
  // Convert timestamp to base36 for shorter string
  const timestamp = Date.now().toString(36)

  // Generate random string (base36)
  const random = Math.random().toString(36).substring(2, 15)

  return `${prefix}_${timestamp}_${random}`
}

/**
 * Extract timestamp from a generated ID.
 *
 * @param id - ID generated by generateId()
 * @returns Timestamp in milliseconds, or null if invalid
 *
 * @example
 * ```ts
 * const id = generateId()
 * const timestamp = extractTimestamp(id)
 * const date = new Date(timestamp!)
 * ```
 */
export function extractTimestamp(id: string): number | null {
  const parts = id.split('_')
  if (parts.length !== 3) {
    return null
  }

  const timestamp = parseInt(parts[1]!, 36)
  return isNaN(timestamp) ? null : timestamp
}

/**
 * Check if an ID was generated by generateId().
 *
 * @param id - ID to validate
 * @returns true if valid format
 *
 * @example
 * ```ts
 * isValidId('op_l8x9k2_a3b4c5d6') // true
 * isValidId('invalid') // false
 * ```
 */
export function isValidId(id: string): boolean {
  const parts = id.split('_')
  if (parts.length !== 3) {
    return false
  }

  const [prefix, timestamp, random] = parts
  if (!prefix || !timestamp || !random) {
    return false
  }

  // Check if timestamp is valid base36 number
  const ts = parseInt(timestamp, 36)
  if (isNaN(ts)) {
    return false
  }

  // Check if random part looks valid (alphanumeric)
  if (!/^[a-z0-9]+$/.test(random)) {
    return false
  }

  return true
}
